workflows:
  build_ios:
    name: Build iOS with Flutter 3.29.2
    max_build_duration: 60
    environment:
      flutter: "3.29.2"
      xcode: latest
      cocoapods: default
    scripts:
      - name: تنظيف المشروع
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace

      - name: تثبيت الحزم
        script: |
          flutter pub get

      - name: إعداد iOS وتثبيت CocoaPods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..

      - name: بناء تطبيق iOS
        script: |
          flutter build ios --release --no-codesign

      - name: توليد ملف IPA يدويًا
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          cd ../../../

    artifacts:
      - build/ios/ipa/Runner.ipa
