workflows:
  build_ios:
    name: Build iOS with Flutter 3.29.2
    max_build_duration: 60  # ممكن تغيرها حسب متطلباتك
    environment:
      flutter: "3.29.2"
    scripts:
      - name: تنظيف شامل
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/Runner.xcworkspace

      - name: إنشاء هيكل symlinks يدويًا
        script: |
          mkdir -p .symlinks/plugins/connectivity_plus/ios
          curl -o .symlinks/plugins/connectivity_plus/ios/connectivity_plus.podspec \
          https://raw.githubusercontent.com/fluttercommunity/plus_plugins/main/packages/connectivity_plus/connectivity_plus/ios/connectivity_plus.podspec

      - name: إعادة توليد ملفات Flutter
        script: |
          flutter pub get
          flutter pub cache repair

      - name: إعداد iOS وتثبيت CocoaPods
        script: |
          cd ios
          # لو مش موجود Podfile، ننشئ واحد جديد بدون توقيع
          if [ ! -f "Podfile" ]; then
            echo "No Podfile found. Generating one using flutter build ios..."
            flutter build ios --no-codesign
          fi
          pod deintegrate
          rm -rf Pods Podfile.lock
          # تثبيت CocoaPods
          sudo gem install cocoapods
          pod repo update
          pod install --repo-update --verbose
          
      - name: بناء تطبيق iOS
        script: |
          flutter build ios --release --no-codesign