workflows:
  build_ios:
    name: Build iOS with Flutter 3.29.2
    max_build_duration: 60
    environment:
      flutter: "3.29.2"
      xcode: latest
      cocoapods: default
    scripts:
      - name: تنظيف المشروع
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace

      - name: تثبيت الحزم
        script: |
          flutter pub get

      - name: بناء التطبيق iOS
        script: |
          cd ios
          pod install --repo-update
          cd ..
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
