name: giftdose
description: "A new Flutter project."
publish_to: "none"

version: 2.2.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # علشان التطبيق يشتغل بس بالـ UI، كل الباقي متشال مؤقتًا

  # get: ^4.6.6
  # country_picker: ^2.0.27
  # device_info_plus: ^11.3.3
  # pinput: ^5.0.1
  # curved_labeled_navigation_bar: ^2.0.5
  # image_picker: ^1.1.2
  # permission_handler: ^11.3.1
  # flutter_localization: ^0.3.0
  # shared_preferences: ^2.3.3
  # http: ^0.13.6
  # geocoding: ^3.0.0
  # flutter_html: ^3.0.0-beta.2
  # google_api_headers: ^4.4.3
  # google_maps_webservice: ^0.0.19
  # badges: ^3.1.2
  # flutter_local_notifications: ^18.0.1
  # geolocator: ^13.0.3
  # dio: ^5.8.0+1
  # flutter_contacts: ^1.1.9+2
  # firebase_core: ^3.10.1
  # firebase_messaging: ^15.2.1
  # google_maps_flutter: ^2.5.0
  # connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_launcher_icons: "^0.14.3"
  # flutter_lints: ^3.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "images/logo.png"
#   remove_alpha_ios: true
#   min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo.png
    - images/avatar.png
    - images/GTIF.jpg

  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf
