platform :ios, '13.0'

target 'Runner' do
  use_frameworks! :linkage => :static # أضف هذه السطر
  
  # استخدم المسار المطلق بدلاً من النسبي
  pod 'connectivity_plus', :path => File.join('.symlinks', 'plugins', 'connectivity_plus', 'ios')
  
  # باقي التبعيات
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # أضف هذه الإعدادات الجديدة
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework "Flutter"'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    # أضف هذا الجزء لتحديث إعدادات Flutter
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end